core/urls.py
from django.urls import path

from core.views import HomeView, HelperCreateView, HelperResultView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('SantaHelper/list/', HelperCreateView.as_view(), name='helper_list'),
    path('SantaHelper/result/', HelperResultView.as_view(), name='result'),
]

santa_claus_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models


class SantaHelper(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, default='Santa helper')
    remote_addr = models.CharField(max_length=20, null=True)

    class Meta:
        unique_together = ('name', 'remote_addr')

    def __str__(self):
        return self.name

core/forms.py
from django import forms


class HelperForm(forms.Form):
    name = forms.CharField(max_length=30, required=True)

core/views.py
import random

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, FormView

from core.forms import HelperForm
from core.models import SantaHelper


class HomeView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        ip_number = request.META['REMOTE_ADDR']
        SantaHelper.objects.filter(remote_addr=ip_number).delete()
        return super().get(request, *args, **kwargs)


class HelperCreateView(ListView, FormView):
    title = 'Add helper'
    template_name = 'helper_list.html'
    form_class = HelperForm
    success_url = reverse_lazy('core:helper_list')
    model = SantaHelper

    def post(self, request, *args, **kwargs):
        helper_name = request.POST['name']
        ip_number = request.META['REMOTE_ADDR']

        if not HelperCreateView.model.objects.filter(name=helper_name, remote_addr=ip_number).exists():
            HelperCreateView.model.objects.create(name=helper_name, remote_addr=ip_number)

        return HttpResponseRedirect(HelperCreateView.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ip_number'] = self.request.META['REMOTE_ADDR']
        return context


class HelperResultView(View):
    def _draw_grantees(self, helpers):
        grantees = []
        for_draw = [_ for _ in helpers]
        for name in helpers:
            grantee = random.choice(for_draw)
            while grantee == name:
                grantee = random.choice(for_draw)
            grantees.append(grantee)
            for_draw.remove(grantee)
        return grantees

    def post(self, request):
        ip_number = request.META['REMOTE_ADDR']
        santa_helpers = SantaHelper.objects.filter(remote_addr=ip_number)

        helper_names = [helper.name for helper in santa_helpers]
        grantee_names = helper_names
        if len(helper_names) > 1:
            grantee_names = self._draw_grantees(helper_names)
        helper_grantee_pairs = tuple(zip(helper_names, grantee_names))

        context = {'pairs': helper_grantee_pairs}
        return render(request, template_name='result.html', context=context)

core/templates/helper_list.html
{% extends "index.html" %}

{% block content %}

  <div class="mx-auto" style="width: 300px;">

    {% for helper in object_list %}
      {% if helper.remote_addr == ip_number %}
        {{ helper.name }} <br/>
      {% endif %}
    {% endfor %}

    <form method="post">
      {% csrf_token %}
      <table>{{ form }}</table>
      <input type="submit" value="Add Santa Helper" class="btn btn-success">
    </form>

    <table class="mx-auto" style="width: 100px;">
      <tr>
        <td>
        <form action="{% url 'core:result' %}" method="post">
          {% csrf_token %}
          <button type='submit' class="btn btn-danger">Draw</button>
        </form>
        </td>
        <td>
        <form action="{% url 'core:home' %}" method="get">
          <button type='submit' class="btn btn-warning">Clear</button>
        </form>
        </td>
      </tr>
    </table>

  </div>

{% endblock %}

core/templates/index.html
​
{% load bootstrap4 %}
{% load static %}
<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Santa Claus helpers</title>
    ​<link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>

  <body class="text-center p-3 mb-2 bg-success text-white">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active text-white" href="{% url 'core:home' %}">Home</a>
            <a class="nav-link text-white" href="https://en.wikipedia.org/wiki/Saint_Nicholas">Santa Claus</a>
            <a class="nav-link text-white" href="https://gitlab.com/mattelega">Contact</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        {% block content %}
          <h2 class="cover-heading" style="color:red">Let's help Santa Claus!</h2>
          <p class="lead">This app will help you choose who you are making a gift to.
                          Just name the people between whom the draw is to take place...</p>
          <p class="lead">
            <a href="{% url 'core:helper_list' %}" class="btn btn-lg btn-danger">Let's start!</a>
          </p>
        {% endblock %}
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p style="font-size: 14px">thank You God for the pleasure of coding :)</p>
          <p style="font-size: 14px">&copy; Mateusz Telega 2020 <a class="text-white" href="https://gitlab.com/mattelega">@GitLab</a></p>
        </div>
      </footer>
    </div>
  </body>
</html>

core/templates/result.html
{% extends "index.html" %}

{% block content %}

  <div class="mx-auto" style="width: 300px;">
  {% if pairs %}
    {% for pair in pairs %}
      <span>
        {% for name in pair %}
          {% if forloop.counter == 1 %}
            {{ name }}
          {% else %}
            -> {{ name }}
          {% endif %}
        {% endfor %}
      </span><br/>
    {% endfor %}
    <br/>
    <a href="{% url 'core:home' %}" class="btn btn-lg btn-success">Home</a>

  {% else %}
    <p>You did not add any person for draw.</p>
    <a href="{% url 'core:helper_list' %}" class="btn btn-lg btn-danger">Let's start!</a>
  {% endif %}
  </div>

{% endblock %}